3.8: add holo-realtek-firmware-toggles, lib32-libssh2, libssh2, update steamos-log-submitter, steamos-systemreport
Update Changes (28.61 MiB):
- holo-realtek-firmware-toggles-1.1-1.src.tar.gz (0.00 MiB)
- lib32-libssh2-1.11.1-2.1.src.tar.gz (13.80 MiB)
- libssh2-1.11.1-4.1.src.tar.gz (13.80 MiB)
- steamos-log-submitter-0.8.2-1.src.tar.gz (1.00 MiB)
- steamos-systemreport-0.19.1-1.src.tar.gz (0.00 MiB)

diff --git a/steamos-systemreport/steamos-systemreport b/steamos-systemreport/steamos-systemreport
--- a/steamos-systemreport/steamos-systemreport
+++ b/steamos-systemreport/steamos-systemreport
@@ -54,7 +54,7 @@ function run {
   echo "---------------------------------------------------"
   echo "Command: $1"
   echo
-  bash -c "$1 2>&1" || echo "Unable to run command!"
+  PAGER=cat SYSTEMD_PAGER=cat bash -c "$1 2>&1" || echo "Unable to run command!"
 }
 
 function super () {
@@ -118,7 +118,8 @@ super bootconfig
 super storage-health
 
 # WiFi connection info
-run 'iwctl station wlan0 show | grep -E "State|Frequency|RSSI|Mode|MCS|Bitrate"'
+run 'iw dev wlan0 link'
+run 'iw dev wlan0 survey dump'
 
 # Network connectivity info
 run 'ip addr'
