main: update dirlock
Update Changes (39.80 MiB):
- dirlock-0.0.1.160.9e3b956-1.src.tar.gz (39.80 MiB)

diff --git a/dirlock/steamos-decrypt-home b/dirlock/steamos-decrypt-home
--- a/dirlock/steamos-decrypt-home
+++ b/dirlock/steamos-decrypt-home
@@ -12,8 +12,26 @@ GREEN="\033[0;32m"
 CYAN="\033[0;36m"
 NC="\033[0m"
 
+tempdir="/home/dirlock.tmp"
+
+cleanup() {
+    if [ -d "$tempdir" ]; then
+        echo "Cleaning temporary directory $tempdir, please wait"
+        rm -rf "$tempdir"
+    fi
+}
+
+trap cleanup INT EXIT
+
 if [ "$(id -u)" != 0 ]; then
     echo "This tool needs to be run as root" >&1
+    exit 1
+fi
+
+if [ -z "${SSH_CONNECTION:-}" ]; then
+    echo -e "${RED}WARNING${NC}: You should be running this tool as root from an ssh connection."
+    echo "It's important that you ssh directly as root rather than using sudo from"
+    echo "a regular 'deck' user session."
     exit 1
 fi
 
@@ -76,16 +94,14 @@ stop_sddm() {
 }
 
 decrypt_home() {
-    tempdir=$(mktemp -d /home/dirlock.tmp.XXXXXX)
-    trap "test -d $tempdir && rm -rf $tempdir" INT EXIT
-
-    echo -en "** ${CYAN}Decrypting /home/deck (this can take a while)${NC}: "
-    cp -a /home/deck "$tempdir/deck"
+    echo -e "** ${CYAN}Decrypting /home/deck (this can take a while)${NC}"
+    rm -rf "$tempdir"
+    mkdir -p "$tempdir"
+    rsync -aAXH --open-noatime --info=progress2 /home/deck/ "$tempdir/deck/"
     sync
     exch /home/deck "$tempdir/deck"
     sync
     rm -rf "$tempdir"
-    echo -e "${GREEN}OK${NC}"
 
     echo -e "** ${CYAN}Setting a new password for the deck user (/etc/shadow)${NC}"
     passwd deck
@@ -115,6 +131,11 @@ The following tasks will be performed now:
 - The system will be rebooted
 
 EOF
+if [ -z "${TMUX:-}" ]; then
+    echo -e "${RED}WARNING${NC}: You don't seem to be running this script from a tmux session."
+    echo "It's recommended to do it in case you lose the network connection."
+    echo
+fi
 echo -e "${RED}WARNING${NC}: This feature is currently experimental."
 echo "Use it at your own risk and make a backup first if you have valuable data."
 echo
