main: update dirlock
Update Changes (55.70 MiB):
- dirlock-0.0.1.185.6162298-1.src.tar.gz (55.70 MiB)

diff --git a/dirlock/steamos-decrypt-home b/dirlock/steamos-decrypt-home
--- a/dirlock/steamos-decrypt-home
+++ b/dirlock/steamos-decrypt-home
@@ -35,13 +35,24 @@ if [ -z "${SSH_CONNECTION:-}" ]; then
     exit 1
 fi
 
+check_encryption_enabled() {
+    echo -en "** ${CYAN}Checking if encryption is enabled${NC}: "
+    if dirlock status -b /home/deck &> /dev/null; then
+        echo -e "${GREEN}OK${NC}"
+    else
+        echo -e "${RED}NO${NC}"
+        echo "ERROR: Encryption does not seem to be enabled" >&2
+        return 1
+    fi
+}
+
 check_unencrypted_home() {
     echo -en "** ${CYAN}Checking if /home/deck is encrypted${NC}: "
     if dirlock status -b /home/deck | grep -qwE 'locked|unlocked'; then
         echo -e "${GREEN}OK${NC}"
     else
         echo -e "${RED}NO${NC}"
-        echo "ERROR: /home/deck is already unencrypted" >&2
+        echo "ERROR: /home/deck is not encrypted by dirlock" >&2
         return 1
     fi
 }
@@ -146,6 +157,7 @@ if [ "$n" != "y" ]; then
     exit 0
 fi
 
+check_encryption_enabled
 check_unencrypted_home
 check_unlocked_home
 check_free_space
